pagopa/gitops

azure-devops/projects/io-backend-projects/provider.tf
azure-devops/projects/io-backend-projects/secrets.tf

This PR add secrets management reading values from azure keyvault.
for **pagopa-github-bot-ro-TOKEN** (read-only) create a personal access token with this permissions:
- admin:repo_hook, read:user, user:email
for **pagopa-github-bot-rw-TOKEN** (read-write) create a personal access token with this permissions:
- read:user, repo, user:email
for **pagopa-github-bot-pr-TOKEN** (pull request) create a personal access token with this permissions:
- public_repo
Update TOKEN values into azure keyvault

[#176654017] Add secrets management

---

azure-devops/projects/io-backend-projects/service_connections.tf

This PR connect Azure DevOps Project with Azure Subscriptions DEV-IO and PROD-IO.
Status: not applied

[#176653696] Add Azure Service Connections

---

azure-devops/projects/io-backend-projects/secrets.tf
azure-devops/projects/io-backend-projects/service_connections.tf

This PR connect Azure DevOps Project with Github with personal access tokens
Status: not applied
Blocked by https://www.pivotaltracker.com/story/show/176900745

[#176653851] Add Github Service Connections

---

azure-devops/projects/io-backend-projects/service_connections.tf

this PR:
- remove github pr service connection
- rename github service connection (remove TOKEN)
- add ignore_changes on authorization scheme not present in documentation https://registry.terraform.io/providers/microsoft/azuredevops/latest/docs/resources/serviceendpoint_github#auth_personal

[#176653851] Fix Github service connection

---

azure-devops/projects/io-backend-projects/service_connections.tf

this pr add a service connection named `pagopa` used to access to azure-pipelines template repo
Status: applied

[#176966332] Add pagopa Github Service Connection

---

azure-devops/projects/io-backend-projects/io-functions-services-cache.tf

this pr create pipelines for new azure function https://github.com/pagopa/io-functions-services-cache

[#ENTE-68] Create io-functions-services pipelines

---

azure-devops/projects/cgn-onboarding-portal-projects/cgn-onboarding-portal-frontend.tf
azure-devops/projects/hub-pa-projects/hub-pa-api.tf
azure-devops/projects/hub-pa-projects/hub-pa-fe.tf
azure-devops/projects/io-backend-projects/io-functions-pushnotifications.tf
azure-devops/projects/io-backend-projects/io-functions-services-cache.tf

this pr contains changes proposed here:
1. https://github.com/pagopa/gitops/pull/20#discussion_r613045969
2. https://github.com/pagopa/gitops/pull/20#discussion_r613044287

[#IOINFRA-66] Review service connection auth names

---

azure-devops/projects/io-pay-projects/io-pay.tf
azure-devops/projects/io-pay-projects/project.tf
azure-devops/projects/io-pay-projects/provider.tf
azure-devops/projects/io-pay-projects/secrets.tf
azure-devops/projects/io-pay-projects/service_connections.tf
azure-devops/projects/io-pay-projects/time_sleep.tf

This PR adds new project for [io-pay](https://github.com/pagopa/io-pay).
- new folder for the new _io-pay_ project with basic configuration;
- new _io-pay.tf_  file with _code-review_ and _deploy_ pipelines with related variables.

[IOPAY-136] new project for io-pay

---

azure-devops/projects/io-backend-projects/io-backend.tf
azure-devops/projects/io-backend-projects/io-functions-app.tf
azure-devops/projects/io-pay-projects/io-pay.tf
azure-devops/projects/io-pay-projects/project.tf
azure-devops/projects/io-pay-projects/provider.tf
azure-devops/projects/io-pay-projects/secrets.tf
azure-devops/projects/io-pay-projects/service_connections.tf
azure-devops/projects/io-pay-projects/time_sleep.tf

Add deploy and code-review pipelines for `io-functions-app`.
Connections and providers are shared with other project in `io-backend-projects`

[#IP-49] Configure pipelines for `io-functions-app`

---

azure-devops/projects/io-backend-projects/io-functions-admin.tf

Add deploy and code-review pipelines for `io-functions-admin.
Connections and providers are shared with other project in `io-backend-projects`

[#IP-49] Configure pipelines for `io-functions-admin` 

---

azure-devops/projects/io-backend-projects/io-backend.tf
azure-devops/projects/io-backend-projects/io-functions-admin.tf
azure-devops/projects/io-backend-projects/io-functions-app.tf
azure-devops/projects/io-backend-projects/io-functions-services.tf
azure-devops/projects/io-pay-projects/io-pay.tf
azure-devops/projects/io-pay-projects/project.tf
azure-devops/projects/io-pay-projects/provider.tf
azure-devops/projects/io-pay-projects/secrets.tf
azure-devops/projects/io-pay-projects/service_connections.tf
azure-devops/projects/io-pay-projects/time_sleep.tf

Add deploy and code-review pipelines for `io-functions-services`.
Connections and providers are shared with other project in `io-backend-projects`.

[#IO-49] Configure pipelines for `io-functions-services`

---

azure-devops/projects/io-backend-projects/io-backend.tf
azure-devops/projects/io-backend-projects/io-functions-admin.tf
azure-devops/projects/io-backend-projects/io-functions-app.tf
azure-devops/projects/io-backend-projects/io-functions-public.tf
azure-devops/projects/io-backend-projects/io-functions-services.tf
azure-devops/projects/io-pay-projects/io-pay.tf
azure-devops/projects/io-pay-projects/project.tf
azure-devops/projects/io-pay-projects/provider.tf
azure-devops/projects/io-pay-projects/secrets.tf
azure-devops/projects/io-pay-projects/service_connections.tf
azure-devops/projects/io-pay-projects/time_sleep.tf

Add deploy and code-review pipelines for `io-functions-public`.
Connections and providers are shared with other project in `io-backend-projects`

[#IP-49] Configure pipelines for `io-functions-public`

---

azure-devops/projects/io-backend-projects/io-backend.tf
azure-devops/projects/io-backend-projects/io-functions-admin.tf
azure-devops/projects/io-backend-projects/io-functions-app.tf
azure-devops/projects/io-backend-projects/io-functions-assets.tf
azure-devops/projects/io-backend-projects/io-functions-public.tf
azure-devops/projects/io-backend-projects/io-functions-services.tf
azure-devops/projects/io-pay-projects/io-pay.tf
azure-devops/projects/io-pay-projects/project.tf
azure-devops/projects/io-pay-projects/provider.tf
azure-devops/projects/io-pay-projects/secrets.tf
azure-devops/projects/io-pay-projects/service_connections.tf
azure-devops/projects/io-pay-projects/time_sleep.tf

Add deploy and code-review pipelines for `io-functions-assets`.
Connections and providers are shared with other project in `io-backend-projects`.

[#IP-49] Configure pipelines for `io-functions-assets`

---

azure-devops/projects/io-backend-projects/io-functions-cgn-merchant.tf
azure-devops/projects/io-backend-projects/io-functions-cgn.tf

Add CGN functions

---

azure-devops/projects/cgn-onboarding-portal-projects/cgn-onboarding-portal-backend.tf
azure-devops/projects/cgn-onboarding-portal-projects/cgn-onboarding-portal-frontend.tf
azure-devops/projects/cgn-onboarding-portal-projects/project.tf
azure-devops/projects/cgn-onboarding-portal-projects/provider.tf
azure-devops/projects/cgn-onboarding-portal-projects/secrets.tf
azure-devops/projects/cgn-onboarding-portal-projects/service_connections.tf

- Add deploy and code-review pipelines for [cgn-onboarding-portal-backend](https://github.com/pagopa/cgn-onboarding-portal-backend)
- Update deploy pipeline for [cgn-onboarding-portal-frontend](https://github.com/pagopa/cgn-onboarding-portal-frontend)

PE-46 Add backend pipelines and update frontend

---

azure-devops/projects/cgn-onboarding-portal-projects/cgn-onboarding-portal-backend.tf
azure-devops/projects/cgn-onboarding-portal-projects/cgn-onboarding-portal-frontend.tf
azure-devops/projects/cgn-onboarding-portal-projects/project.tf
azure-devops/projects/cgn-onboarding-portal-projects/provider.tf
azure-devops/projects/cgn-onboarding-portal-projects/service_connections.tf

this pr:
1. disable not used project-features
2. disable allow_override variable setting
3. update azuredevops provider to 0.1.4
4. switch to azure_devops_org to pagopaspa
5. other minor fix

[#IOINFRA-72] Update configuration with more strict permissions 

---

azure-devops/projects/pagopa-packages-projects/io-spid-commons.tf

Adding io-spid-commons to pagopa packages

Adding io-spid-commons to gitops

---

azure-devops/projects/pagopa-packages-projects/ts-commons.tf

Configure core review and deploy pipelines for `@pagopa/ts-commons` package in the `pagopa-packages-project` project

[#IP-157] Add pipeline definitions for `@pagopa/ts-commons`

---

azure-devops/projects/cgn-onboarding-portal-projects/cgn-onboarding-portal-backend.tf
azure-devops/projects/cgn-onboarding-portal-projects/cgn-onboarding-portal-frontend.tf
azure-devops/projects/cgn-onboarding-portal-projects/project.tf
azure-devops/projects/cgn-onboarding-portal-projects/provider.tf
azure-devops/projects/cgn-onboarding-portal-projects/secrets.tf
azure-devops/projects/cgn-onboarding-portal-projects/service_connections.tf
azure-devops/projects/io-backend-projects/io-functions-cgn-merchant.tf
azure-devops/projects/io-backend-projects/io-functions-cgn.tf
azure-devops/projects/io-pay-projects/io-functions-pay-portal.tf
azure-devops/projects/io-pay-projects/io-pay-portal-fe.tf
azure-devops/projects/io-pay-projects/io-pay.tf
azure-devops/projects/io-pay-projects/project.tf
azure-devops/projects/io-pay-projects/provider.tf
azure-devops/projects/io-services-metadata-projects/io-services-metadata.tf
azure-devops/projects/io-services-metadata-projects/project.tf
azure-devops/projects/io-services-metadata-projects/provider.tf
azure-devops/projects/io-services-metadata-projects/secrets.tf
azure-devops/projects/io-services-metadata-projects/service_connections.tf
azure-devops/projects/io-services-metadata-projects/time_sleep.tf
azure-devops/projects/pagopa-packages-projects/io-functions-commons.tf
azure-devops/projects/pagopa-packages-projects/io-spid-commons.tf
azure-devops/projects/pagopa-packages-projects/project.tf
azure-devops/projects/pagopa-packages-projects/provider.tf
azure-devops/projects/pagopa-packages-projects/secrets.tf
azure-devops/projects/pagopa-packages-projects/service_connections.tf
azure-devops/projects/pagopa-packages-projects/time_sleep.tf
azure-devops/projects/pagopa-packages-projects/ts-commons.tf

- Add deploy and code-review pipelines for [io-pay-portal-fe](https://github.com/pagopa/io-pay-portal/tree/main/io-pay-portal-fe);
- Add deploy and code-review pipelines for [io-functions-pay-portal](https://github.com/pagopa/io-pay-portal/tree/main/io-functions-pay-portal);

[IOPAY-148] Configure pipelines for io-pay-portal-fe and io-functions-pay-portal

---

azure-devops/projects/io-pay-projects/io-pay.tf

- updated _PaymentManager_ endpoint for production;

[IOPAY-175] update PaymentManager endpoint for prod

---

azure-devops/projects/cgn-onboarding-portal-projects/io-functions-cgn-operator-search.tf
azure-devops/projects/io-backend-projects/io-functions-cgn-operator-search.tf

https://github.com/pagopa/io-functions-cgn-operator-search

Add io-functions-cgn-operator-search

---

azure-devops/projects/hub-pa-projects/hub_pa_fe.tf

This PR proposes to add many variables to support deploy of PTT in UAT.
- Storage account name
- Cdn endpoint name
- Cdn profile name
- Frontend resource group name
- Container and index name

[PTT-85] Add storage/cdn variables for hub-pa-fe to support deploy in UAT

---

azure-devops/projects/cgn-onboarding-portal-projects/ade-aa-ms-mock.tf

https://github.com/pagopa/ade-aa-ms-mock/pull/1

Add ade-aa-ms-mock

---

azure-devops/projects/cgn-onboarding-portal-projects/cgn-onboarding-portal-frontend.tf

https://dev.azure.com/pagopaspa/cgn-onboarding-portal-projects/_build/results?buildId=372&view=logs&j=52f3644b-5100-5a23-7390-edc5c1058d80&t=5eadd0cc-821c-5aa4-19ee-94121b6d3d1a&l=54
```
ERROR: (ResourceGroupNotFound) Resource group 'cgnonboardingportal-u-cdn-rg' could not be found.
```

Fix resource group for cdn

---

azure-devops/projects/cert-az-management/api-cgnonboardingportal-pagopa-it.tf
azure-devops/projects/cert-az-management/api-cgnonboardingportal-uat-pagopa-it.tf
azure-devops/projects/cert-az-management/api.hubpad.pagopa.it.tf
azure-devops/projects/cert-az-management/project.tf
azure-devops/projects/cert-az-management/provider.tf
azure-devops/projects/cert-az-management/secrets.tf
azure-devops/projects/cert-az-management/service_connections.tf
azure-devops/projects/cert-az-management/uat-cgnonboardingportal-pagopa-it.tf

create new certaz renew certificates for:
1. api.cgnonboardingportal.pagopa.it [PROD]
2. api.cgnonboardingportal-uat.pagopa.it [UAT]
please @AleDore @ElfoLiNk check names

Add certaz project and api cgnonboardingportal

---

azure-devops/projects/cgn-onboarding-portal-projects/io-functions-cgn-operator-search.tf

https://github.com/pagopa/io-functions-cgn-operator-search/pull/9

PE-66 Update deploy env vars gcn os

---

azure-devops/projects/io-backend-projects/io-functions-services.tf

https://github.com/pagopa/io-functions-services/pull/122

Update endpoint user fn-services

---

azure-devops/projects/io-backend-projects/io-functions-app.tf

https://github.com/pagopa/io-functions-app/pull/176

[#IP-286] Update pipelines fn3app

---

.tflint.hcl
azure-devops/projects/sitecorporate-projects/project.tf
azure-devops/projects/sitecorporate-projects/provider.tf
azure-devops/projects/sitecorporate-projects/secrets.tf
azure-devops/projects/sitecorporate-projects/service_connections.tf

Add sitecorporate project

---

azure-devops/projects/io-app-projects/io-cie-sdk.tf
azure-devops/projects/io-app-projects/project.tf
azure-devops/projects/io-app-projects/provider.tf
azure-devops/projects/io-app-projects/secrets.tf
azure-devops/projects/io-app-projects/service_connections.tf

- Add new `io-app` project
- Add new `io-cie-sdk` pipelines folder with code-review and deploy

Add new `io-app` project with `io-cie-sdk` pipelines

---

azure-devops/projects/cert-az-management-projects/app-api-io-pagopa-it.tf

add certificate for new endpoint app-api.io.pagopa.it

Add app-api.io.pagopa.it certificate

---

azure-devops/projects/pagopa-packages-projects/express-azure-functions.tf
azure-devops/projects/pagopa-packages-projects/io-spid-commons.tf
azure-devops/projects/pagopa-packages-projects/openapi-codegen-ts.tf
azure-devops/projects/pagopa-packages-projects/provider.tf
azure-devops/projects/pagopa-packages-projects/secrets.tf
azure-devops/projects/pagopa-packages-projects/service_connections.tf
azure-devops/projects/pagopa-packages-projects/ts-commons.tf

Add  `@pagopa/express-azure-functions` pipelines to `pagopa-packages-projects`

Add pipelines for `@pagopa/express-azure-functions`

---

azure-devops/projects/cstar-projects/fa-ms-customer.tf

This PR requests to add code review and deploy pipelines for FA Customer Microservice

[CEN-668] Code Review and Deploy Pipelines for FA Customer Microservice

---

azure-devops/projects/pagopa-projects/pagopa-mock-psp.tf

- added pipelines for `pagopa-mock-psp;`

[PM-164] mock psp pipeline

---

azure-devops/projects/pagopa-projects/pagopa-api-config.tf
azure-devops/projects/pagopa-projects/service_connections.tf
azure-devops/projects/pagopa-projects/time_sleep.tf

**List of changes**
- added pipelines for `pagopa-api-config`;

[PCFG-14] added pipeline configuration for `@pagopa/pagopa-api-config` repo

---

azure-devops/projects/cstar-projects/fa-ms-file-storage.tf

This PR proposes to add a code review and a deploy pipeline for the FA File Storage microservice

[CEN-681] Pipeline for FA File Storage microservice

---

azure-devops/projects/cstar-projects/fa-ms-invoice-manager.tf

This PR proposes to add a code review and a deploy pipeline for FA Invoice Manager microservice

[CEN-679] Pipeline for FA Invoice Manager microservice

---

azure-devops/projects/cstar-projects/fa-ms-merchant.tf

This PR proposes to add a code review and a deploy pipeline for the FA Merchant microservice

[CEN-678] Pipelines for FA Merchant microservice

---

azure-devops/projects/cstar-projects/fa-ms-notification-manager.tf

This PR proposes to add a code review and a deploy pipeline for the microservice Notification Manager

[CEN-677] Pipelines for FA Notification Manager microservice

---

azure-devops/projects/cstar-projects/fa-ms-onboarding-merchant.tf

This PR proposes to add a code review and a deploy pipeline for the FA Onboarding Merchant microservice

[CEN-676] Pipelines for FA Onboarding Merchant microservice

---

azure-devops/projects/cstar-projects/fa-ms-payment-instrument.tf

This PR proposes to add a code review and a deploy pipeline for the FA Payment Instrument microservice

[CEN-675] Pipelines for FA Payment Instrument Microservice

---

azure-devops/projects/cstar-projects/fa-ms-transaction.tf

This PR proposes to add a code review and a deploy pipeline for the FA Transaction microservice

[CEN-674] Pipelines for FA Transaction Microservice

---

azure-devops/projects/cstar-projects/fa-ms-starter-parent.tf

This PR proposes to add a pipeline to deploy to Azure Devops a POM common to all microservices

[CEN-673] Pipeline to Deploy a POM Common to all Microservices

---

azure-devops/projects/cstar-projects/fa-commons.tf

This PR proposes to add code review and deploy pipelines for `fa-common` library

[CEN-672] Pipeline for FA common library fa-commons

---

azure-devops/projects/cstar-projects/fa-ms-customer.tf
azure-devops/projects/cstar-projects/fa-ms-enrollment.tf

This PR proposes to add code review and deploy pipelines for FA Enrollment microservice, plus a minor fix in Customer's pipelines.

[CEN-669] Pipelines for FA Microservice Enrollment

---

azure-devops/projects/eucovidcert-projects/io-functions-eucovidcerts.tf
azure-devops/projects/eucovidcert-projects/locals.tf
azure-devops/projects/io-backend-projects/io-backend.tf
azure-devops/projects/io-backend-projects/io-functions-admin.tf
azure-devops/projects/io-backend-projects/io-functions-app.tf
azure-devops/projects/io-backend-projects/io-functions-assets.tf
azure-devops/projects/io-backend-projects/io-functions-public.tf
azure-devops/projects/io-backend-projects/io-functions-services.tf
azure-devops/projects/io-backend-projects/io-pagopa-proxy.tf
azure-devops/projects/io-backend-projects/locals.tf
azure-devops/projects/io-developer-portal-projects/io-developer-portal-backend.tf

Create a shared reference to the custom linux agent for deploy pipelines

[#IP-401] set `AGENT_POOL` variable for IO projects

---

azure-devops/projects/pagopa-iac-projects/iac.tf
azure-devops/projects/pagopa-iac-projects/locals.tf
azure-devops/projects/pagopa-iac-projects/project.tf
azure-devops/projects/pagopa-iac-projects/provider.tf
azure-devops/projects/pagopa-iac-projects/secrets.tf
azure-devops/projects/pagopa-iac-projects/service_connections.tf
azure-devops/projects/pagopa-projects/service_connections.tf

Add pagoPA-iac project and pipelines

Add pagoPA iac pipelines

---

azure-devops/projects/io-backend-projects/io-functions-pushnotifications.tf

Add missing AGENT_POOL variable to `io-functions-pushnotification`

Add missing AGENT_POOL variable to `io-functions-pushnotification`

---

azure-devops/projects/selfcare-iac-projects/iac.tf
azure-devops/projects/selfcare-iac-projects/locals.tf
azure-devops/projects/selfcare-iac-projects/project.tf
azure-devops/projects/selfcare-iac-projects/provider.tf
azure-devops/projects/selfcare-iac-projects/secrets.tf
azure-devops/projects/selfcare-iac-projects/service_connections.tf

selfcare iac project devops

---

azure-devops/projects/io-backend-projects/io-functions-publiceventdispatcher.tf

[#IP-455] Define pipelines for io-functions-publiceventdispatcher (more fixes) 

---

azure-devops/projects/selfcare-projects/locals.tf
azure-devops/projects/selfcare-projects/selc-uservice-party-process.tf

interop services deploy pipeline configuration
---

defining interop pipeline configuration

---

azure-devops/projects/selfcare-projects/locals.tf
azure-devops/projects/selfcare-projects/selc-uservice-party-management.tf

selfcare party management deployment pipeline
---

selfcare party management

---

azure-devops/projects/selfcare-projects/selc-fe-dashboard.tf
azure-devops/projects/selfcare-projects/selc-fe-login.tf
azure-devops/projects/selfcare-projects/selc-fe-onboarding.tf

FE review on PR enabled

---

azure-devops/projects/pagopa-projects/tlscert-dev-api-config-dev-platform-pagopa-it.tf
azure-devops/projects/pagopa-projects/tlscert-uat-api-config-uat-platform-pagopa-it.tf

fix apiconfig dns_record_name
---

fix apiconfig dns_record_name

---

azure-devops/projects/pagopa-packages-frontend-projects/secrets.tf
azure-devops/projects/pagopa-packages-frontend-projects/service_connections.tf

Switch to pagopa npm

---

azure-devops/projects/pagopa-projects/locals.tf
azure-devops/projects/pagopa-projects/pagopa-api-config-fe.tf
azure-devops/projects/pagopa-projects/pagopa-checkout-io-pay-portal-fe.tf
azure-devops/projects/pagopa-projects/pagopa-checkout-io-pay.tf
azure-devops/projects/pagopa-projects/pagopa-nodo-pagamenti.tf
azure-devops/projects/pagopa-projects/provider.tf
azure-devops/projects/pagopa-projects/service_connections.tf
azure-devops/projects/pagopa-projects/tlscert-dev-api-dev-platform-pagopa-it.tf
azure-devops/projects/pagopa-projects/tlscert-dev-config-dev-plaform-pagopa-it.tf
azure-devops/projects/pagopa-projects/tlscert-dev-dev-checkout-pagopa-it.tf
azure-devops/projects/pagopa-projects/tlscert-dev-management-dev-platform-pagopa-it.tf
azure-devops/projects/pagopa-projects/tlscert-dev-portal-dev-platform-pagopa-it.tf
azure-devops/projects/pagopa-projects/tlscert-prod-api-platform-pagopa-it.tf
azure-devops/projects/pagopa-projects/tlscert-prod-checkout-pagopa-it.tf
azure-devops/projects/pagopa-projects/tlscert-prod-config-prod-plaform-pagopa-it.tf
azure-devops/projects/pagopa-projects/tlscert-prod-management-platform-pagopa-it.tf
azure-devops/projects/pagopa-projects/tlscert-prod-portal-platform-pagopa-it.tf
azure-devops/projects/pagopa-projects/tlscert-uat-api-uat-platform-pagopa-it.tf
azure-devops/projects/pagopa-projects/tlscert-uat-config-uat-plaform-pagopa-it.tf
azure-devops/projects/pagopa-projects/tlscert-uat-management-uat-platform-pagopa-it.tf
azure-devops/projects/pagopa-projects/tlscert-uat-portal-uat-platform-pagopa-it.tf
azure-devops/projects/pagopa-projects/tlscert-uat-uat-checkout-pagopa-it.tf

refactor tlscert definitions to upgrade 2.0.2 version
- better service connection management
- change tlscert_renew_token value and apply to renew all tls-certs service connections
---

refactor to version 2.0.2

---

azure-devops/projects/selfcare-projects/locals.tf
azure-devops/projects/selfcare-projects/selc-uservice-attribute-registry-management.tf
azure-devops/projects/selfcare-projects/selc-uservice-party-management.tf
azure-devops/projects/selfcare-projects/selc-uservice-party-process.tf
azure-devops/projects/selfcare-projects/selc-uservice-party-registry-proxy.tf

Interop services configured
---

Selfcare interop service config

---

azure-devops/projects/cgn-onboarding-portal-projects/cgn-onboarding-portal-backend.tf
azure-devops/projects/cgn-onboarding-portal-projects/service_connections.tf

enable prod container registry connetcion
---

add container registry connection strng

---

azure-devops/projects/selfcare-projects/locals.tf
azure-devops/projects/selfcare-projects/selc-onboarding-backend.tf

added b4f-onboarding-backend
---

added onboarding-backend

---

azure-devops/projects/pagopa-projects/pagopa-nodo-pagamenti.tf

The purpose of this PR is to add : 
- `sia_docker_registry`
- `sia_docker_username`
- `sia_docker_password`
variables and set `ci_trigger_use_yaml = true` for code review.
---

[PAG-1012] add sia docker registry info

---

azure-devops/projects/selfcare-projects/hub-spid-login-ms.tf
azure-devops/projects/selfcare-projects/secrets.tf
azure-devops/projects/selfcare-projects/selc-dashboard-backend.tf
azure-devops/projects/selfcare-projects/selc-ms-product.tf
azure-devops/projects/selfcare-projects/selc-onboarding-backend.tf
azure-devops/projects/selfcare-projects/selc-uservice-attribute-registry-management.tf
azure-devops/projects/selfcare-projects/selc-uservice-party-management.tf
azure-devops/projects/selfcare-projects/selc-uservice-party-process.tf
azure-devops/projects/selfcare-projects/selc-uservice-party-registry-proxy.tf
azure-devops/projects/selfcare-projects/service_connections.tf

prod-uat-selfcare

---

azure-devops/projects/pagopa-projects/pagopa-nodo-pagamenti-devops.tf

The purpose of this PR is to create the AZ DevOps project for the test repo [pagopa-nodo4-nodo-dei-pagamenti-devops](https://github.com/pagopa/pagopa-nodo4-nodo-dei-pagamenti-devops)
---

create pipeines prj pagopa-nodo4-nodo-dei-pagamenti-devops

---

azure-devops/projects/io-developer-portal-projects/locals.tf
azure-devops/projects/io-developer-portal-projects/project.tf
azure-devops/projects/io-developer-portal-projects/provider.tf
azure-devops/projects/io-developer-portal-projects/service_connections.tf
azure-devops/projects/io-developer-portal-projects/tlscert-prod-api-io-selfcare-pagopa-it.tf
azure-devops/projects/io-developer-portal-projects/tlscert-prod-io-selfcare-pagopa-it.tf

add tls cert for io selfcare
---

add-tls-cert-for-io-selfcare

---

azure-devops/projects/io-developer-portal-projects/io-developer-portal-backend.tf

Fix resource values after #208

[#IC-148] Fix values for `SelfCare IO`

---

azure-devops/projects/io-backend-projects/io-functions-cgn-merchant.tf
azure-devops/projects/io-backend-projects/io-functions-cgn.tf

Added vars for CGN deploy pipelines

---

azure-devops/projects/selfcare-projects/locals.tf

added cdn and storage urls

---

azure-devops/projects/pagopa-projects/pagopa-api-config.tf

The purpose of this PR is to add Az container registry variable used by Az pipelines for [pagopa-api-config](https://github.com/pagopa/pagopa-api-config)
---

[PCFG-103] add acr section

---

azure-devops/projects/pagopa-projects/pagopa-proxy.tf

- add code review / deploy pipeline configurations for `pagopa-proxy` in [pagopa-projects Azure Devops](https://dev.azure.com/pagopaspa/pagoPA-projects)
The goal of this PR is to add new pipelines for [pagopa-proxy](https://github.com/pagopa/io-pagopa-proxy/tree/master/src) in order to deploy on new _pagoPA Azure subscriptions_.
This configuration expects:
- code review pipeline defined in `io-pagopa-proxy/.devops/pagopa-code-review-pipelines.yml`
- deploy pipeline defined in `io-pagopa-proxy/.devops/pagopa-deploy-pipelines.yml`
---

[IOPAY-404] add pagopa-proxy pipeline in pagopa subscription

---

azure-devops/projects/io-developer-portal-projects/io-developer-portal-backend.tf

migrate devportal to selfcare
---

migrate-devportal

---

azure-devops/projects/pagopa-projects/pagopa-proxy.tf

- add `dev_azure_subscription` in order to deploy `pagopa-propxy` on DEV subscription
---

[IOPAY-403] add dev subscription for pagopa-proxy

---

azure-devops/projects/pagopa-projects/pagopa-api-config.tf
azure-devops/projects/pagopa-projects/pagopa-functions-buyerbank.tf
azure-devops/projects/pagopa-projects/pagopa-proxy.tf

- Add code-review pipeline for pagopa-buyerbank Azure functions
- Add  deploy pipeline for pagopa-buyerbank Azure functions
- New product
---

[PM-386] Add deploy/code-review pipeline for buyerbank

---

azure-devops/README.md
azure-devops/projects/selfcare-projects/hub-spid-login-ms.tf
azure-devops/projects/selfcare-projects/locals.tf
azure-devops/projects/selfcare-projects/provider.tf
azure-devops/projects/selfcare-projects/secrets.tf
azure-devops/projects/selfcare-projects/selc-be-commons.tf
azure-devops/projects/selfcare-projects/selc-be-starter-parent.tf
azure-devops/projects/selfcare-projects/selc-dashboard-backend.tf
azure-devops/projects/selfcare-projects/selc-fe-dashboard.tf
azure-devops/projects/selfcare-projects/selc-fe-login.tf
azure-devops/projects/selfcare-projects/selc-fe-onboarding.tf
azure-devops/projects/selfcare-projects/selc-ms-product.tf
azure-devops/projects/selfcare-projects/selc-onboarding-backend.tf
azure-devops/projects/selfcare-projects/selc-uservice-attribute-registry-management.tf
azure-devops/projects/selfcare-projects/selc-uservice-party-management.tf
azure-devops/projects/selfcare-projects/selc-uservice-party-process.tf
azure-devops/projects/selfcare-projects/selc-uservice-party-registry-proxy.tf
azure-devops/projects/selfcare-projects/service_connections.tf
azure-devops/projects/selfcare-projects/tlscert-dev-api-dev-selfcare-pagopa-it.tf
azure-devops/projects/selfcare-projects/tlscert-dev-dev-selfcare-pagopa-it.tf
azure-devops/projects/selfcare-projects/tlscert-prod-api-selfcare-pagopa-it.tf
azure-devops/projects/selfcare-projects/tlscert-prod-selfcare-pagopa-it.tf
azure-devops/projects/selfcare-projects/tlscert-uat-api-uat-selfcare-pagopa-it.tf
azure-devops/projects/selfcare-projects/tlscert-uat-uat-selfcare-pagopa-it.tf
azure-devops/terraform.sh

* added triggers on cert pipelines
* added new script terraform.sh to simplify the work
* pre-commit changes
new triggers to avoid certificates to expires

INFRA-400-in-gitops-aggiungere-scheduled-trigger-le-pipeline-dei-certificati-ssl

---

azure-devops/projects/io-backend-projects/io-openid-provider.tf

- Add io-openid-provider code review build definition.
We need the automated part of the code review process to be applied to the new io-openid-provider project.
---

Add io-openid-provider code review build definition

---

azure-devops/projects/selfcare-projects/secrets.tf
azure-devops/projects/selfcare-projects/selc-fe-common.tf
azure-devops/projects/selfcare-projects/service_connections.tf

added pipeline to handle selfcare-common-frontend project

---

azure-devops/projects/selfcare-projects/selc-fe-common.tf

added npm_connection deploy var
---

added npm_connection deploy var

---

azure-devops/projects/selfcare-projects/locals.tf
azure-devops/projects/selfcare-projects/selc-fe-assistance.tf
azure-devops/projects/selfcare-projects/selc-ms-notification-manager.tf

Added pipelines to review/deploy selfcare-assistance-frontend and selfcare-ms-notification-manager
---

Selfcare assistance services

---

azure-devops/projects/selfcare-projects/locals.tf

fixed notification-manager api url
---

SELC-410 fixed notification-manager api url

---

azure-devops/projects/io-developer-portal-projects/io-subscription-migrations.tf
azure-devops/projects/io-developer-portal-projects/secrets.tf
azure-devops/projects/io-developer-portal-projects/service_connections.tf

[#IC-188] Add NPM subscription

---

azure-devops/projects/pagopa-projects/pagopa-functions-fdr.tf

The purpose of this PR is to create CI/CD Az devops project for [flussi di rendicontazione](https://github.com/pagopa/pagopa-reporting-fdr)
Add : 
- `pagopa-functions-fdr.tf` CI and CD pipelines
---

[PMF-10] add Flussi Di Rendicontazione CI CD pipelines prj

---

azure-devops/projects/pagopa-projects/pagopa-debt-position.tf

The purpose of this PR is to create CI/CD Az devops project for [deb-position](https://github.com/pagopa/pagopa-debt-position)
Add : 
- `pagopa-debt-position.tf` CI and CD pipelines
---

[PPD-52] add Debt Position CI CD pipelines prj

---

azure-devops/projects/pagopa-projects/pagopa-functions-fdr.tf

The purpose of this PR is to add sonar cloud service connection
Add : 
- `SONARCLOUD-SERVICE-CONN` service connection
-  
---

[PMF-10] add sonar cloud service connection to Fdr repo

---

azure-devops/projects/pagopa-projects/pagopa-functions-fdr.tf

The purpose of this PR is to update CI vars
---

[PMF-11] Update vars fdr CI pipelines

---

azure-devops/projects/cstar-projects/rtd-ms-ingestor.tf

This PR proposes to add code review and deploy pipelines for microservice `rtd-ms-ingestor`
- New pipelines and related variables and service connection
This PR is useful to create a new microservice capable of ingesting transactions on rtd queue
---

[CEN-1358] Add pipelines for rtd-ms-ingestor

---

azure-devops/projects/cstar-projects/rtd-ms-decrypt.tf

This PR proposes to create variables and service connections for `rtd-ms-decrypter` pipelines
- variables and service connections `rtd-ms-decrypter` pipelines
This microservice is useful to decrypt files uploaded by acquirers on cstar blob storage
---

[CEN-1358] Add rtd-ms-decrypter pipelines

---

azure-devops/projects/io-backend-projects/io-functions-app-message-test.tf

Add Io-functions-app-message-test
Create new functions-app for testing message purpose
---

add fn-app-message-test

---

azure-devops/projects/pagopa-projects/pagopa-payment-transactions-gateway.tf

- Add code review pipeline for `pagopa-payment-transactions-gateway`;
---

[PM-451] CR for pagopa-payment-transactions-gateway

---

azure-devops/projects/pagopa-projects/pagopa-checkout-fe.tf

[IOPAY-481] Add Checkout v2 FE pipeline

---

azure-devops/projects/pagopa-projects/pagopa-payment-transactions-gateway.tf

-  Add auth for sonar cloud service connection;
---

Add auth for sonar cloud service connection

---

azure-devops/projects/pagopa-projects/pagopa-canone-unico.tf

[PDD-101]  canone unico

---

azure-devops/projects/selfcare-projects/selc-ms-user-group.tf

Added ms-user-group pipelines
---

added ms-user-group pipelines

---

azure-devops/projects/pagopa-projects/pagopa-canone-unico.tf
azure-devops/projects/pagopa-projects/pagopa-debt-position.tf

fix names of the functions
---

Fix Canone Unico Name

---

azure-devops/projects/selfcare-projects/selc-uservice-party-management.tf
azure-devops/projects/selfcare-projects/selc-uservice-party-process.tf
azure-devops/projects/selfcare-projects/selc-uservice-party-registry-proxy.tf

party application devops2.0
---

SelfCare party applicationd devops 2.0

---

azure-devops/projects/io-backend-projects/io-functions-app-messages.tf
azure-devops/projects/io-backend-projects/io-functions-services-cache.tf

[#IC-312] Rename fn-app-messages

---

azure-devops/projects/io-backend-projects/io-functions-messages-cqrs.tf

Add app names to function cqrs

---

azure-devops/projects/io-iac-projects/iac.tf
azure-devops/projects/io-iac-projects/service_connections.tf

add prod-io-sign service connection
---

add prod-io-sign service connection

---

azure-devops/projects/selfcare-projects/locals.tf
azure-devops/projects/selfcare-projects/selc-fe-dashboard-groups.tf
azure-devops/projects/selfcare-projects/selc-fe-dashboard-users.tf

Added pipeline to review and deploy dashboard microfrontends
---

new pipeline to serve micro-frontends

---

azure-devops/projects/io-iac-projects/iac.tf
azure-devops/projects/io-iac-projects/service_connections.tf
azure-devops/projects/io-iac-projects/service_connections_reminder.tf
azure-devops/projects/io-iac-projects/service_connections_sign.tf

add reminder service connection

---

azure-devops/projects/io-backend-projects/io-premium-reminder-ms.tf
azure-devops/projects/io-backend-projects/service_connections.tf

add io-reminder ms

---

azure-devops/projects/io-iac-projects/iac.tf
azure-devops/projects/io-iac-projects/service_connections_aks.tf

add aks service connection

---

azure-devops/projects/selfcare-projects/locals.tf

Configured UAT OneTrust domain id
Configured PROD OneTrust domainId 
fixed notificationManager URL
---

uat OneTrust domainId

---

azure-devops/projects/cstar-commons.tf

This PR proposes to create new pipelines to automate CI/CD of library in repository `cstar-commons`.
- New code-review pipeline
- New deploy pipeline
This PR solves the problem of automating CI/CD for library cstar-commons
---

[RTD-78] Add pipelines cstar commons

---

azure-devops/projects/cstar-projects/rtd-ms-file-register.tf

This PR proposes to add a code review and a deploy pipelines to implement CI/CD for micro-service `rtd-ms-file-register`
- A new code-review pipeline
- A new deploy pipeline
This PR is required to implement CI/CD for micro-service `rtd-ms-file-register`
---

[RTD-81] Add code-review and deploy pipelines

---

azure-devops/projects/io-backend-projects/io-functions-service-messages.tf

- Add `io-functions-service-messages`
Enable pipelines permissions for new repo https://github.com/pagopa/io-functions-service-messages
---

[#IC-474] Add Functions Service Messages

---

azure-devops/projects/pagopa-packages-projects/express-azure-functions.tf
azure-devops/projects/pagopa-packages-projects/io-template-typescript.tf
azure-devops/projects/pagopa-packages-projects/provider.tf

Added code review pipeline for io-template-typescript 
io-template-typescript is using circleci, a migration to azure is needed
---

Add pipelines for io-template-typescript

---

azure-devops/projects/io-backend-projects/io-functions-public.tf

Updated io-functions-public pipeline

---

azure-devops/projects/pagopa-packages-projects/handler-kit.tf

Add pipelines for "@pagopa/handler-kit" package (NPM)

---

azure-devops/projects/io-backend-projects/io-functions-sign.tf

Add "io-sign" deploy pipeline

---

azure-devops/projects/io-backend-projects/io-functions-sign.tf

Add io sign deploy pipeline (fix already applied)

---

azure-devops/projects/cgn-onboarding-portal-projects/io-functions-cgn-operator-search.tf

fix operator search

---

azure-devops/projects/cstar-iac-projects/03_iac.tf
azure-devops/projects/pagopa-packages-projects/danger-plugin.tf
azure-devops/projects/sites-projects/04_io-italia-it.tf

Cstar-iac-fix-github-service-connection

---

azure-devops/projects/selfcare-projects/selc-be-commons.tf
azure-devops/projects/selfcare-projects/selc-be-starter-parent.tf
azure-devops/projects/selfcare-projects/selc-dashboard-backend.tf
azure-devops/projects/selfcare-projects/selc-fe-assistance.tf
azure-devops/projects/selfcare-projects/selc-fe-common.tf
azure-devops/projects/selfcare-projects/selc-fe-dashboard-groups.tf
azure-devops/projects/selfcare-projects/selc-fe-dashboard-users.tf
azure-devops/projects/selfcare-projects/selc-fe-dashboard.tf
azure-devops/projects/selfcare-projects/selc-fe-login.tf
azure-devops/projects/selfcare-projects/selc-fe-onboarding.tf
azure-devops/projects/selfcare-projects/selc-ms-notification-manager.tf
azure-devops/projects/selfcare-projects/selc-ms-product.tf
azure-devops/projects/selfcare-projects/selc-ms-user-group.tf
azure-devops/projects/selfcare-projects/selc-onboarding-backend.tf
azure-devops/projects/selfcare-projects/selc-uservice-party-management.tf
azure-devops/projects/selfcare-projects/selc-uservice-party-mock-registry.tf
azure-devops/projects/selfcare-projects/selc-uservice-party-process.tf
azure-devops/projects/selfcare-projects/selc-uservice-party-registry-proxy.tf

Prod-selfcare-june-15

---

azure-devops/projects/io-iac-projects/README.md
azure-devops/projects/io-iac-projects/backups.tf
azure-devops/projects/io-iac-projects/iac.tf
azure-devops/projects/io-iac-projects/provider.tf
azure-devops/projects/io-iac-projects/variables.tf

new pipeline to run apim backups

---

azure-devops/projects/pagopa-packages-projects/io-pagopa-commons.tf

Add io-pagopa-commons pipelines

---

azure-devops/projects/pagopa-packages-projects/fp-ts-kafka-js.tf

Add fp-ts-kafkajs project

---

azure-devops/projects/pagopa-packages-projects/fp-ts-kafka-js.tf
azure-devops/projects/pagopa-packages-projects/provider.tf

Add fp ts kafkajs project

---

azure-devops/projects/pagopa-packages-projects/fp-ts-kafka-js.tf

The pipelines has problem to run on main branch, to fix that we moved it to master
---

fix: changed master branch to master

---

.pre-commit-config.yaml
.utils/terraform_run_all.sh
azure-devops/projects/io-backend-projects/io-functions-sign.tf
azure-devops/projects/selfcare-projects/selc-be-commons.tf
azure-devops/projects/selfcare-projects/selc-be-starter-parent.tf
azure-devops/projects/selfcare-projects/selc-dashboard-backend.tf
azure-devops/projects/selfcare-projects/selc-fe-assistance.tf
azure-devops/projects/selfcare-projects/selc-fe-common.tf
azure-devops/projects/selfcare-projects/selc-fe-dashboard-groups.tf
azure-devops/projects/selfcare-projects/selc-fe-dashboard-users.tf
azure-devops/projects/selfcare-projects/selc-fe-dashboard.tf
azure-devops/projects/selfcare-projects/selc-fe-login.tf
azure-devops/projects/selfcare-projects/selc-fe-onboarding.tf
azure-devops/projects/selfcare-projects/selc-ms-notification-manager.tf
azure-devops/projects/selfcare-projects/selc-ms-product.tf
azure-devops/projects/selfcare-projects/selc-ms-user-group.tf
azure-devops/projects/selfcare-projects/selc-onboarding-backend.tf
azure-devops/projects/selfcare-projects/selc-uservice-party-management.tf
azure-devops/projects/selfcare-projects/selc-uservice-party-mock-registry.tf
azure-devops/projects/selfcare-projects/selc-uservice-party-process.tf
azure-devops/projects/selfcare-projects/selc-uservice-party-registry-proxy.tf

- added utils/terraform_run_all.sh to allow to re-install all the modules and providers, in case of errors duriong pre-commit
- upgraded pre-commit version
- fix pre-commit warnings
pre-commit modify a lot of file, and is better to mantain the base code clean
---

Pre-commit-fixes

---

azure-devops/projects/selfcare-projects/selc-external-api-backend.tf

adding devops for new selfcare microservices

---

azure-devops/projects/cstar-projects/rtd-ms-sender-auth.tf

This PR proposes to add the CI/CD pipelines for the sender-auth micro service.
- Add pipelines
---

[RTD-191] add ci/cd pipelines for rtd-ms-sender-auth

---

azure-devops/projects/cstar-projects/rtd-ms-enrolled-payment-instrument.tf

- added pipelines configuration for CI/CD of `rtd-ms-enrolled-payment-instrument`.
---

[RTD-293] added ci/cd pipelines for enrolled-payment-instrument ms

---

azure-devops/projects/cstar-iac-projects/04_backups.tf
azure-devops/projects/cstar-iac-projects/99_variables.tf

Apim backup pipeline

---

azure-devops/projects/cstar-iac-projects/04_backups.tf
azure-devops/projects/io-iac-projects/backups.tf

Change main branch in scheduled pipeline

---

azure-devops/projects/io-iac-projects/backups.tf

Io apim backup in business hours

---

azure-devops/projects/io-developer-portal-projects/io-developer-portal-service-data.tf

Define pipelines for https://github.com/pagopa/io-developer-portal-service-data
Define pipelines for https://github.com/pagopa/io-developer-portal-service-data
---

[#IOPSC-62] Add pipelines for developer-portal-service-data

---

azure-devops/projects/selfcare-projects/locals.tf

Using same DEV mixPanel token for UAT
---

using MixPanel token DEV also in UAT

---

azure-devops/projects/cstar-projects/bpd-io-backend-test.tf

This service should be deployable in prod for FA test
---

[CSFA-68] Add deploy to prod

---

azure-devops/projects/selfcare-projects/selc-ms-party-registry-proxy.tf

Signed-off-by: andrea-putzu <andrea.putzu@pagopa.it>
Adding new BE for manage IPA documents creating a local search engine
Adding code.review and deploy pipeline for selfcare-ms-party-registry-proxy
---

feat: Adding selfcare-party-registry-proxy BE

---

azure-devops/projects/io-backend-projects/io-functions-assets.tf

Change to new fn-assets target

---

azure-devops/projects/io-developer-portal-projects/io-developer-portal-service-data.tf

Developer Portal Service Data Project pipeline fix to resolve an issue that prevents us to build our deploy code.
* Add variable `AGENT_POOL` to the Azure Code Deploy Pipeline to Developer Portal Service Data Project
Agent pool variable need to be set in order to deploy the code

add AGENT_POOL variable to deploy pipeline

---

azure-devops/projects/cstar-projects/rtd-ms-pi-event-processor.tf

This PR adds code-review and deploy pipelines to new pi-event-processor microservice
---

[RTD-781] Add pipelines to rtd-ms-pi-event-processor

---

azure-devops/projects/cstar-projects/rtd-ms-file-reporter.tf

This PR proposes to create the code review and deploy pipelines for the new micro-service file-reporter.
- add pipelines definition
---

[RTD-893] add ci/cd pipelines for rtd-ms-file-reporter

---

azure-devops/projects/eucovidcert-projects/io-functions-eucovidcerts.tf

See commit list
As we are upgrading Azure Functions engine to v4, we needed to create a brand new resource. We are going to deploy code on this.
Depends on https://github.com/pagopa/io-functions-eucovidcerts/pull/102
Depends on https://github.com/pagopa/io-infra/pull/306/
---

[#IOPAE-98] Deploy `fn-eucovidcerts` to new resource

---

azure-devops/projects/selfcare-projects/selc-core-backend.tf
azure-devops/projects/selfcare-projects/selc-social-login-backend.tf

Adding new Selfcare Core and Social login microservices pipeline core_review and deploy.
---

fix: ADD MS-Core and MS-Social-login pipelines code_review/deploy

---

azure-devops/projects/io-backend-projects/io-functions-cgn-merchant.tf

NOTE: PR related to https://github.com/pagopa/io-infra/pull/312
* changed resource group name
* changed app_name
new rg and name for cgn-merchant
---

[#IOCIT-183] edited cgn-merchant pipeline variables

---

azure-devops/projects/io-backend-projects/io-functions-public.tf

* edited function-public pipeline variables
new resource group and function name
---

[#IOCIT-182] edited function-public pipeline variables

---

azure-devops/projects/io-backend-projects/io-functions-pushnotifications.tf

[#IOCIT-177] Update Pushnotif pipeline

---

azure-devops/projects/io-developer-portal-projects/io-selfcare-importadesioni.tf

* define code-review and deploy pipeline
Pipeline defined in https://github.com/pagopa/io-selfcare-importadesioni
---

[#IOPAE-128] Pipeline definitions for `io-selfcare-importadesioni`

---

azure-devops/projects/io-backend-projects/io-functions-publiceventdispatcher.tf

Deploy `fn-pblevtdispatcher` to new resources defined in https://github.com/pagopa/io-infra/pull/416
Depends on https://github.com/pagopa/io-infra/pull/416
---

Change `fn-pblevtdispatcher` resource

---

azure-devops/projects/io-backend-projects/io-functions-lollipop.tf

Add new Functions Lollipop pipelines

---

azure-devops/projects/io-backend-projects/io-functions-pushnotifications.tf

Update fn-pushnotif variables, removed danger toked
---

Update fn-pushnotif variables

---

azure-devops/projects/io-backend-projects/tlscert-prod-continua-io-pagopa-it.tf

- define  tlscert pipeline for continua.io.pagopa.it
Create and rotate tls certificate for continua.io.pagopa.it
---

dynamiclink: add tlscert for continua.io.pagopa.it

---

azure-devops/projects/io-services-metadata-projects/io-services-metadata.tf
azure-devops/projects/io-services-metadata-projects/service_connections.tf

Replace CDN parameters with the new value for `io-services-metadata` pipeline.
The purge CDN task fail because the CDN was migrated.
---

Change CDN parameters for services-metadata

---

azure-devops/projects/cgn-onboarding-portal-projects/README.md
azure-devops/projects/cgn-onboarding-portal-projects/service_connections.tf

add renew service principal credentials CGN portal

---

azure-devops/projects/io-backend-projects/tlscert-prod-firma-io-italia-it.tf

- Defined pipeline for TLS certificate firma.io.italia.it
A TLS certificate is needed to deploy the landing page
---

feat(io-sign): [SFEQS-1658] Add TLS cert for firma.io.italia.it

---

azure-devops/projects/io-backend-projects/io-functions-fast-login.tf

* see commit history
add `io-functions-fast-login` pipelines
---

[#IOPID-262] add io-functions-fast-login pipelines

---

azure-devops/projects/io-developer-portal-projects/locals.tf
azure-devops/projects/io-developer-portal-projects/tlscert-prod-api-io-selfcare-pagopa-it.tf
azure-devops/projects/io-developer-portal-projects/tlscert-prod-io-selfcare-pagopa-it.tf

#SELC-2147 Update Selfcare TLS cert Renew token

---

azure-devops/projects/pagopa-packages-projects/hub-spid-login.tf
azure-devops/projects/pagopa-packages-projects/io-web-hub-spid-login.tf

This PR depends on https://github.com/pagopa/io-infra/pull/654
* Added needed resources
Adding pipelines into project `pagopa-packages-projects` for hub-spid-login microservice. Those are needed for io-web portal
---

[#IOPID-577] created needed resources
